# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  assignmentcloud:
    image: assignmentcloud
    build:
      context: .
      dockerfile: Assignment-Cloud/Dockerfile
    ports:
      - 8080:8080
